katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls'))
]

todolist/urls.py
from django.urls import path
from todolist.views import create_task, delete_task, register, show_task, update_task
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import post_ajax_todolist, show_json, show_json_by_id, show_todolist_ajax

app_name = 'todolist'

urlpatterns = [
    path('', show_task, name='show_task'),  
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('add/', create_task, name='create_task'),
    path('update-task/<int:id>', update_task, name='update_task'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('ajax/', show_todolist_ajax, name='show_todolist_ajax'),
    path('ajax/submit', post_ajax_todolist, name="post_ajax_todolist")
]

todolist/models.py
from datetime import datetime
from xmlrpc.client import DateTime
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model

class Task(models.Model):
    user = models.ForeignKey(User, models.SET_NULL, blank=True, null=True)
    date = models.DateTimeField(default=datetime.now())
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import Task
from django.forms import ModelForm

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
            'title',
            'description'
        ]

todolist/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from todolist.models import Task
from todolist.forms import TaskForm
import json
from django.http import HttpResponse, JsonResponse
from django.core import serializers



@login_required(login_url='/todolist/login/')
def show_task(request):
    task_data = Task.objects.filter(user=request.user)
    context = {
        'list_task' : task_data,
        'last_login' : request.COOKIES['last_login']
    }
    return render(request, 'todolist.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_task")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

@login_required(login_url='/todolist/login/')
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def create_task(request):
    form = TaskForm()

    if request.method == "POST":
        form = TaskForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            messages.success(request, 'Berhasil membuat task!')
            return redirect('todolist:show_task')

    context = {'form': form}
    return render(request, 'create_task.html', context)

@login_required(login_url='/todolist/login/')
def update_task(request, id):
    task_list = Task.objects.filter(id=id)
    task = task_list[0]
    task.is_finished = not task.is_finished
    task.save()
    return redirect('todolist:show_todolist_ajax')

@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    Task.objects.filter(id=id).delete()
    return redirect('todolist:show_todolist_ajax')

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    task_list = Task.objects.all()
    context = {
    'list_task': task_list,
    'last_login': request.COOKIES['last_login']
    }
    return render(request, "todolist_ajax.html", context)


def post_ajax_todolist(request):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']

        ins = Task(title=title, description=description)
        ins.save()

        data = {
            "message" : 'Submitted!'
        }
        json_obj = json.dumps(data, indent = 4)

        return JsonResponse(json.loads(json_obj))
    return render(request, "create_task.html")

def show_json(request):
    data = Task.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Task.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create a Task</title>
{% endblock meta %}

{% block content %}  

<center>
    <h1>Create Task</h1>
<center>

<div class="addtodolist d-flex justify-content-center align-items-center">

    <form method="POST" action="" class="d-flex flex-column">
      {% csrf_token %}
      <div class="form d-flex flex-column justify-content-between gap-2">
        <label for="title">Judul</label>
        <input
          name="title"
          id="title"
          placeholder="Title"
        />
      </div>
      <div class="form d-flex flex-column justify-content-between gap-2">
        <label for="deskripsi">Deskripsi</label>
        <input
          name="description"
          id="description"
          placeholder="Description"
        />
      </div>
      <button class="btn btn-success">Submit</button>
    </form>
    <center>
        <center id="message"></center>
    <center>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $('form').submit(function (event) {
      const formData = {
        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
        title: $('#title').val(),
        description: $('#description').val(),
      };

      $.ajax({
        type: 'POST',
        url: '/todolist/ajax/submit',
        data: formData,
        dataType: 'json',
        encode: true,
      }).done(function (data) {
        $('#message').text(data.message);
      });

      event.preventDefault();
    });
  });
</script>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<style>
    table, th, td{
    border: 1px solid black;
  }
</style>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="mx-auto navbar-brand disabled" href="#">Selamat Datang, {{user}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          <a class="nav-link" href="{% url 'todolist:create_task' %}">Create Task</a>
        </li>
      </ul>
    </div>
</nav>

<table class="table table-hover w-50 mx-auto table-bordered">
    <tr class="thead-dark">
    <th scope="col" >Tanggal</th>
    <th scope="col" >Judul</th>
    <th scope="col" >Deskripsi</th>
    <th scope="col" >Status</th>
    <th scope="col" >Actions</th>
    </tr>

{% for task in list_task %}
    <tr>
        <th>{{task.date}}</th>
        <th>{{task.title}}</th>
        <th>{{task.description}}</th>
        <th>{{task.is_finished}}</th>
        <td><button><a href="{% url 'todolist:update_task' task.id %}">Done</a></button></td>
        <td><button><a href="{% url 'todolist:delete_task' task.id %}">Delete</a></button></td>
    </tr>
{% endfor %}
</table>

<h5 class="w-50 mx-auto" >Sesi terakhir login: {{ last_login }}</h5>


{% endblock content %} 
 

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block content %}

<style>
    table, th, td{
    border: 1px solid black;
  }
</style>

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="mx-auto navbar-brand disabled" href="#">Selamat Datang, {{user}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todolist:logout' %}">Logout</a>
          <a class="nav-link" href="{% url 'todolist:create_task' %}">Create Task</a>
        </li>
      </ul>
    </div>
</nav>

<table class="table table-hover w-50 mx-auto table-bordered">
    <tr class="thead-dark">
    <th scope="col" >Tanggal</th>
    <th scope="col" >Judul</th>
    <th scope="col" >Deskripsi</th>
    <th scope="col" >Status</th>
    <th scope="col" >Actions</th>
    </tr>

{% for task in list_task %}
    <tr>
        <th>{{task.date}}</th>
        <th>{{task.title}}</th>
        <th>{{task.description}}</th>
        <th>{{task.is_finished}}</th>
        <td><button><a href="{% url 'todolist:update_task' task.id %}">Done</a></button></td>
        <td><button><a href="{% url 'todolist:delete_task' task.id %}">Delete</a></button></td>
    </tr>
{% endfor %}
</table>

<h5 class="w-50 mx-auto" >Sesi terakhir login: {{ last_login }}</h5>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
    $(document).ready(function(){
      $.get("/todolist/json", function(data) {
        data.map((each) =>
            $('#table').append(`<tr>
        <td>${each.fields.title}</td>
        <td>${each.fields.description}</td>
        </tr>`)
        );
        });
    });
</script>


{% endblock content %} 
 